#!/bin/sh

NAME=MODULE_NAME
VERSION=MODULE_VERSION

set -e

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $NAME -v $VERSION --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

echo "Unloading driver from kernel"
rmmod pibook-hid-driver
echo "Removing driver from autoload"
grep -v "pibook-hid-driver" /etc/modules > /etc/modules_temp
mv /etc/modules_temp /etc/modules

exit 0


